name: Build J2V8
on: [push]

jobs:
  generate_j2v8_archives:
    strategy:
      fail-fast: true
      matrix:
        target: [win32,linux] 
        include:
          - target: win32
            os: windows-latest
          - target: linux
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    name: Build for ${{ matrix.target }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
        
    - name: Setup MSBuild
      if: ${{ matrix.target }} == "win32"
      uses: microsoft/setup-msbuild@v1.0.1
        
        
    - name: Download monolithic libraries to v8.out directory and bundle Linux jar and Android aar file
      shell: bash
      run: |
        curl -O https://download.eclipsesource.com/j2v8/v8/libv8_8.3.110.9_monolith.zip
        mkdir -p v8.out
        unzip libv8_8.3.110.9_monolith.zip -d v8.out

        # start j2v8 build
        if [ "${{ matrix.target }}" = "win32" ];
        then
          python build.py -t win32 -a x64 j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java j2v8test
        elif [ "${{ matrix.target }}" = "linux" ];
        then
          python build.py -t linux -a x64 --docker j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java j2v8test
        else 
          echo "Invalid target ${{ matrix.target }}"
          exit 1
        fi
        #python build.py -t linux -a x64 --docker j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java j2v8test
        #python build.py -t android -a x86 --docker --keep-native-libs j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java
        #python build.py -t android -a arm --docker --keep-native-libs j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java
        #python build.py -t android -a x86_64 --docker --keep-native-libs j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java
        #python build.py -t android -a arm64 --docker --keep-native-libs j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java


    - name: Archive J2V8 Android aar file
      uses: actions/upload-artifact@v1.0.0
      with:
        name: j2v8-android-aar
        path: build/outputs/aar/j2v8-release.aar
        
        
    - name: Archive J2V8 Linux x86_64 jar
      uses: actions/upload-artifact@v1.0.0
      with:
        name: j2v8-linux-x86_64
        path: build.out/j2v8_linux_x86_64-6.2.0.jar
        
    - name: Archive J2V8 Windows x86_64 jar
      uses: actions/upload-artifact@v1.0.0
      with:
        name: j2v8-linux-x86_64
        path: build.out/j2v8_windows_x86_64-6.2.0.jar
