name: Build J2V8
on: [push]

jobs:
  generate_j2v8_archives:
    strategy:
      fail-fast: true
      matrix:
        target: [win32,linux] 
        include:
          - target: win32
            os: windows-latest
          - target: linux
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    name: Build for ${{ matrix.target }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
        
    - name: Setup MSBuild
      if: matrix.target == 'win32'
      uses: microsoft/setup-msbuild@v1.0.1
        
    - name: Build for ${{ matrix.target }}
      if: matrix.target == 'win32'
      run: |
        j2v8-cli.cmd
        python build.py -t win32 -a x64 j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java j2v8test
        
